import { type NextPage } from "next";
import { signOut, useSession } from "next-auth/react";
import Head from "next/head";

import Link from "next/link";
import { api } from "../utils/api";

const Home: NextPage = () => {
    const { data: sessionData, status } = useSession();
    const hello = api.example.getAll.useQuery();
    console.log(sessionData);

    if (status === "loading") {
        return <div>Loading...</div>;
    }

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {sessionData ? (
                    <a href="#signout" onClick={(e) => {
                        e.preventDefault();
                        signOut();
                    }}>
                        Sign Out
                    </a>
                ) : (<Link href="/auth/signin">
                    Sign in
                </Link>)}
                <AuthShowcase />
            </main>
        </>
    );
};

export default Home;

const AuthShowcase: React.FC = () => {
    const { data: sessionData } = useSession();

    const { data: secretMessage } = api.example.getSecretMessage.useQuery(
        undefined, // no input
        {
            enabled: sessionData?.user !== undefined
        },
    );

    return (
        <div>
            {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
            {secretMessage && <span> - {secretMessage}</span>}
        </div>
    );
};
